# Jason log configuration for Museum Complex

# default Jason MAS Console
handlers = jason.runtime.MASConsoleLogHandler

.level = INFO

# Jason Handler parameters
jason.runtime.MASConsoleLogHandler.level = ALL
jason.runtime.MASConsoleLogHandler.formatter = jason.runtime.MASConsoleLogFormatter
jason.runtime.MASConsoleLogHandler.tabbed = false
jason.runtime.MASConsoleLogHandler.colors = true

# Console handler (alternative — uncomment to disable GUI console)
#handlers= java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level = FINE
java.util.logging.ConsoleHandler.formatter = jason.runtime.MASConsoleLogFormatter

java.level=OFF
javax.level=OFF
jade.level=OFF
sun.level=OFF
